name: "FRP Client HA版"
slug: "frp_client_ha"
version: "1.25.0"
description: "FRP客户端ha版本，仅可对本地Home Assistant操作系统的远程访问穿透"
url: https://github.com/huxiaoxu2019/hass-addon-frp-client
host_network: true
startup: application
boot: "manual"
init: false
image: ghcr.io/wuwweizn/frp_client_ha-{arch}
map:
  - share:rw
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd6
  - armv7
options:
  server_addr: "frp.freefrp.net"
  server_port: 7000
  token: "12345678"
  proxy_type: http
  proxy_name: "myHA"
  local_port: 8123
  remote_port: 8128
schema:
  server_addr: str
  server_port: int
  token: str
  proxy_type: list(http|tcp)
  proxy_name: str
  local_port: int
  custom_domains: str
  remote_port: match(^([1-4][0-9]{4}|50000|80|443)$)
  subdomain: str?
