version: "3.0.0-alpha.76"
image: ghcr.io/t0bst4r/home-assistant-matter-hub-addon
slug: hamh76
name: Home-Assistant-Matter-Hub (3.0.0-alpha.76)
description: 最后一个 可与 Amazon Alexa 正常配合的稳定版本. 请确保一次只启用 一个 HAMH 插件.
url: https://github.com/t0bst4r/home-assistant-matter-hub
panel_icon: mdi:hub
panel_title: Matter Hub (v76)
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 0
map:
  - addon_config:rw
options:
  app_log_level: info
  disable_log_colors: false
  mdns_network_interface: ""
schema:
  app_log_level: list(silly|debug|info|notice|warn|error|fatal)
  disable_log_colors: bool
  mdns_network_interface: "str?"
