name: Docker Wyze Bridge
version: "2.11.1"
slug: wyze-bridge
description: WebRTC/RTSP/RTMP/HLS bridge for Wyze cams
url: "https://github.com/mrlt8/docker-wyze-bridge"
webui: "http://[HOST]:[PORT:5000]"
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: application
panel_icon: mdi:webcam
image: "mrlt8/wyze-bridge"
environment:
  WB_AUTH: false
  HOME_ASSISTANT: true
ports:
  5000/tcp: Web界面
  8554/tcp: RTSP
  8888/tcp: HLS
  1935/tcp: RTMP
  8889/tcp: WebRTC
ports_description:
  5000/tcp: Web管理界面
  8554/tcp: RTSP流媒体
  8888/tcp: HLS流媒体
  1935/tcp: RTMP流媒体
  8889/tcp: WebRTC
options:
  wyze_email: ""
  wyze_password: ""
  api_id: ""
  api_key: ""
schema:
  wyze_email: str
  wyze_password: password
  api_id: str?
  api_key: str?
map:
  - share:rw
  - media:rw