name: "Calendar Poetry"
version: '1.0.4'
slug: 'calendar-poetry'
codenotary: wuweizhineng@163.com
description: '它是本地日历和古诗词相结合的接口'
image: ghcr.io/wuwweizn/calendar-poetry-{arch}
url: https://github.com/wuwweizn/wwzn-china
init: false
arch:
  - aarch64
  - amd64
ports:
  80/tcp: 13001
  5000/tcp: 13002
apparmor: true
boot: manual
