name: "FRP Client"
description: "您可以使用此工具通过端口转发实现对本地HA的远程访问"
version: "1.0.1"
slug: "frp_client"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  serverAddr: "example.com"
  serverPort: 7000
  authToken: "123456789"
  webServerPort: 7500
  webServerUser: "admin"
  webServerPassword: "123456789"
  customDomain: "example.com"
  proxyName: "homeassistant"
schema:
  serverAddr: str
  serverPort: int
  authToken: str
  webServerPort: int
  webServerUser: str
  webServerPassword: str
  customDomain: str
  proxyName: str
