name: "HA Proxy Env"
version: "1.0.0"
slug: "ha_proxy_env"
description: "为 Home Assistant 设置全局代理环境变量 (HTTP_PROXY/HTTPS_PROXY)"
url: "https://github.com/wuwweizn/wwzn-china"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
options:
  http_proxy: "http://127.0.0.1:7890"
  https_proxy: "http://127.0.0.1:7890"
schema:
  http_proxy: str
  https_proxy: str
init: false
