build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
  armhf: "ghcr.io/home-assistant/armhf-base:3.21"
  armv7: "ghcr.io/home-assistant/armv7-base:3.21"
  i386: "ghcr.io/home-assistant/i386-base:3.21"

labels:
  org.opencontainers.image.title: "v2rayN Home Assistant Add-on"
  org.opencontainers.image.description: "v2rayN proxy client integrated with Home Assistant"
  org.opencontainers.image.source: "https://github.com/wuwweizn/wwzn-china"
  org.opencontainers.image.url: "https://github.com/wuwweizn/wwzn-china/tree/main/v2rayn"
  org.opencontainers.image.licenses: "MIT"
  
args:
  TEMPIO_VERSION: "2021.09.0"