name: "V2Ray Core"
version: "5.24.9.0"
slug: "v2ray"
description: "V2Ray is a platform for building proxies to bypass network restrictions"
url: "https://github.com/wuwweizn/wwzn-china"
arch:
  - amd64
  - aarch64
  - armv7
init: false
map:
  - "config:rw"
  - "ssl:rw"
ports:
  10808/tcp: 10808
  10809/tcp: 10809
ports_description:
  10808/tcp: "SOCKS5 proxy port"
  10809/tcp: "HTTP proxy port"
options:
  log_level: "warning"
  subscription_url: ""
  socks_port: 10808
  http_port: 10809
  update_interval: 24
  auto_start: true
  selected_node: 0
  enable_node_selection: true
schema:
  log_level: "list(debug|info|warning|error|none)"
  subscription_url: "str"
  socks_port: "int(1024,65535)"
  http_port: "int(1024,65535)" 
  update_interval: "int(1,168)"
  auto_start: "bool"
  selected_node: "int"
  enable_node_selection: "bool"
image: "ghcr.io/wuwweizn/v2ray-{arch}"
