build_from:
  aarch64: "ghcr.io/hassio-addons/base-nodejs:16.0.1-aarch64"
  amd64: "ghcr.io/hassio-addons/base-nodejs:16.0.1-amd64"
  armhf: "ghcr.io/hassio-addons/base-nodejs:16.0.1-armhf"
  armv7: "ghcr.io/hassio-addons/base-nodejs:16.0.1-armv7"
  i386: "ghcr.io/hassio-addons/base-nodejs:16.0.1-i386"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: YesPlayMusic"
  org.opencontainers.image.description: "高颜值的第三方网易云音乐播放器"
  org.opencontainers.image.source: "https://github.com/wuwweizn/wwzn-china"
  org.opencontainers.image.licenses: "MIT"
args:
  YESPLAYMUSIC_VERSION: "latest"