build_from:
  aarch64: alpine:latest
  amd64: alpine:latest
  armv7: alpine:latest

labels:
  org.opencontainers.image.title: "YesPlayMusic"
  org.opencontainers.image.description: "高颜值的第三方网易云播放器"
  org.opencontainers.image.source: "https://github.com/qier222/YesPlayMusic"
  org.opencontainers.image.licenses: "MIT"

args:
  YESPLAYMUSIC_VERSION: "v0.4.5"