name: "YesPlayMusic"
version: "0.4.8"
slug: "yesplaymusic"
description: "High-quality third-party NetEase Music client with third-party API"
url: "https://github.com/qier222/YesPlayMusic"
startup: "application"
arch:
  - "amd64"
  - "aarch64"
  - "armv7"
image: "ghcr.io/wuwweizn/yesplaymusic-{arch}"
ports:
  8080/tcp: 8080
options:
  api_url: "http://47.121.211.116:3001"
schema:
  api_url: "str"
