{
  "name": "YesPlayMusic",
  "version": "0.4.7",
  "slug": "yesplaymusic",
  "description": "高颜值的第三方网易云播放器，支持在 Home Assistant 中使用",
  "url": "https://github.com/qier222/YesPlayMusic",
  "startup": "application",
  "panel_icon": "mdi:music",
  "panel_title": "YesPlayMusic",
  "panel_admin": false,
  "arch": [
    "aarch64",
    "amd64",
    "armv7"
  ],
  "ports": {
    "80/tcp": 8080
  },
  "ports_description": {
    "80/tcp": "Web界面端口"
  },
  "webui": "[PROTO:ssl]://[HOST]:[PORT:80]",
  "ingress": true,
  "ingress_port": 80,
  "ingress_stream": false,
  "map": [
    "ssl"
  ],
  "options": {
    "ssl": false,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem",
    "custom_title": "YesPlayMusic",
    "log_level": "info"
  },
  "schema": {
    "ssl": "bool",
    "certfile": "str",
    "keyfile": "str",
    "custom_title": "str",
    "log_level": "list(trace|debug|info|notice|warning|error|fatal)?"
  },
  "environment": {},
  "image": "wbsu2003/yesplaymusic:0.4.7"
}
