name: YesPlayMusic
version: "1.0.0"
slug: yesplaymusic
description: "高颜值的第三方网易云音乐播放器 - A beautiful third-party NetEase Cloud Music player"
url: "https://github.com/stark81/my_yesplaymusic"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: manual
ports:
  "8080/tcp": 8080
ports_description:
  "8080/tcp": "Web interface"
webui: "http://[HOST]:[PORT:8080]"
hassio_api: false
hassio_role: default
homeassistant_api: false
privileged: []
full_access: false
audio: false
video: false
stdin: false
legacy: false
stage: stable
init: false
image: "ghcr.io/wuwweizn/yesplaymusic-{arch}"
options:
  netease_api_url: "http://47.121.211.116:3001"
  port: 8080
schema:
  netease_api_url:
    str?
  port:
    port?
environment:
  VUE_APP_NETEASE_API_URL: "netease_api_url"
  PORT: "port"