name: UnblockNeteaseMusic
version: "1.0.8"
slug: unblock-netease-music
description: "解锁网易云音乐灰色歌曲"
url: "https://github.com/nondanee/UnblockNeteaseMusic"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
boot: manual
options:
  port: 8080
  sources: "kuwo,kugou,migu"
schema:
  port: "int(1024,65535)"
  sources: "str"
ports:
  8080/tcp: null
image: "ghcr.io/wuwweizn/unblock-netease-music-{arch}"
hassio_api: true
hassio_role: default
homeassistant_api: false
host_network: false
full_access: false
apparmor: false