name: "HA System Proxy"
version: "1.0.0"
slug: "ha-system-proxy" 
description: "Configure system-wide proxy for Home Assistant OS"
url: "https://github.com/wuwweizn/wwzn-china"
arch:
  - amd64
  - aarch64
  - armv7
init: false
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
startup: application
boot: auto
options:
  proxy_mode: "selective"
  v2ray_socks_port: 10808
  v2ray_http_port: 10809
  enable_for_supervisor: true
  enable_for_addons: true
  bypass_private_networks: true
  bypass_china_sites: false
  test_connectivity: true
schema:
  proxy_mode: "list(selective|global|disabled)"
  v2ray_socks_port: "int(1024,65535)"
  v2ray_http_port: "int(1024,65535)"
  enable_for_supervisor: "bool"
  enable_for_addons: "bool"
  bypass_private_networks: "bool"
  bypass_china_sites: "bool"
  test_connectivity: "bool"