name: YT Music PO Token Generator
version: 1.2.1
slug: ytm_po_token_generator
description:一个用于 BgUtils POT Provider 的 Home Assistant 插件封装，可为 YouTube Music 生成 PO 令牌.
url: https://github.com/Brainicism/bgutil-ytdlp-pot-provider
image: docker.1ms.run/brainicism/bgutil-ytdlp-pot-provider
arch:
  - amd64
  - aarch64
ports:
  "4416/tcp": 4416
