name: WebTunnel
version: "1.0.0"
slug: webtunnel
description: "WebTunnel - 网络隧道工具"
arch:
  - aarch64
  - amd64
  - armv7
init: false
url: https://github.com/wuwweizn/wwzn-china
image: ghcr.io/wuwweizn/webtunnel-{arch}
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:15.0.1
  amd64: ghcr.io/hassio-addons/base/amd64:15.0.1
  armv7: ghcr.io/hassio-addons/base/armv7:15.0.1
map:
  - config:rw
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "WebTunnel Web Interface"
options:
  server_port: 8080
  log_level: info
schema:
  server_port:
    type: int
    default: 8080
    description: "WebTunnel server port"
  log_level:
    type: list
    default: info
    options:
      - debug
      - info
      - warn
      - error
    description: "Log level"