build_from:
  aarch64: python:3.11-slim
  amd64: python:3.11-slim
  armv7: python:3.11-slim
labels:
  org.opencontainers.image.title: TradingAgents-CN
  org.opencontainers.image.description: 基于多智能体LLM的中文金融交易框架
  org.opencontainers.image.source: https://github.com/wuwweizn/wwzn-china
  org.opencontainers.image.licenses: Apache-2.0