name: TradingAgents-CN
version: "1.0.2"
slug: tradingagents-cn
description: 基于多智能体LLM的中文金融交易框架
arch:
  - amd64
  - arm64
  - armv7
startup: services
boot: auto
host_network: true
webui: "http://[HOST]:8501"
homeassistant: false
ingress: true
panel_icon: "mdi:finance"
map:
  config: true
  data: true
options: {}
schema: {}
image: "ghcr.io/你的用户名/tradingagents-cn:1.0.0"
