build_from:
  armhf: "ghcr.nju.edu.cn/hassio-addons/base-python:17.0.0"
  armv7: "ghcr.nju.edu.cn/hassio-addons/base-python:17.0.0"
  aarch64: "ghcr.nju.edu.cn/hassio-addons/base-python:17.0.0"
  amd64: "ghcr.nju.edu.cn/hassio-addons/base-python:17.0.0"
  i386: "gghcr.nju.edu.cn/hassio-addons/base-python:17.0.0"
