name: LibreTV
version: "2025.08.29"
slug: libretv
codenotary: wuweizhineng@163.com
description: >
  LibreTV 是一个轻量级、免费的在线视频搜索与观看平台，
  提供来自多个视频源的内容搜索与播放服务
url: https://github.com/wuwweizn/
init: false
arch:
  - aarch64
  - amd64
image: ghcr.io/wuwweizn/libretv-{arch}
ports:
  8080/tcp: 8899
webui: http://[HOST]:[PORT:8899]
boot: manual
environment:
  PASSWORD: "1234"
