name: "LibreTV"
version: '202507251119'
slug: 'wg-libretv'
codenotary: wghaos@163.com
description: 'LibreTV 是一个轻量级、免费的在线视频搜索与观看平台，提供来自多个视频源的内容搜索与播放服务'
# image: r.hassbus.com/wghaos/
image: bestzwei/libretv
url: https://gitcode.com/waxgourd/addons
init: false
arch:
  - aarch64
  - amd64
ports:
  8080/tcp: 8899
webui: "[PROTO:http]://[HOST]:[PORT:8899]"
boot: manual
environment:
  PASSWORD: "1234"