name: Cloudflared
version: 5.3.6
slug: cloudflared
description: 使用Cloudflare隧道远程连接到没有的家庭助手
  opening any ports
url: https://github.com/brenner-tobias/addon-cloudflared/
codenotary: dev@brenner.tech
init: false
hassio_api: true
hassio_role: homeassistant
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
options:
  external_hostname: ''
  additional_hosts: []
ports:
  36500/tcp: null
schema:
  external_hostname: str?
  additional_hosts:
  - hostname: str
    service: str
    disableChunkedEncoding: bool?
  tunnel_name: str?
  catch_all_service: str?
  nginx_proxy_manager: bool?
  use_builtin_proxy: bool?
  tunnel_token: str?
  post_quantum: bool?
  run_parameters:
  - match(^(--edge-bind-address|--edge-ip-version|--grace-period|--ha-connections|--logfile|--loglevel|--pidfile|--protocol|--region|--retries|--tag)=.*$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/brenner-tobias/cloudflared/{arch}
