labels:
  maintainer: "Desmond Dong"
  io.hass.addon.changelog: |
    ## [1.5.2] - 2025-01-03
    - Initial release of musicn addon for Home Assistant.
    - First version of music server integration.
  io.hass.addon.version: "1.5.2"
  io.hass.addon.name: "musicn"
  io.hass.addon.description: "一个可播放及下载音乐的 Node.js 工具，目前已经支持国内用户直接安装使用，不用魔法"
  io.hass.addon.url: "https://github.com/Desmond-Dong/hassio-addons"
  io.hass.addon.arch: "aarch64, amd64, armv7"
  io.hass.addon.init: "false"
  io.hass.addon.startup: "services"
  io.hass.addon.ingress: "true"
  io.hass.addon.ingress_port: "7478"
  io.hass.addon.panel_icon: "mdi:music"
  io.hass.addon.ports: |
    7478/tcp: 7478
  io.hass.addon.ports_description: |
    7478/tcp: "Web Server port"
  io.hass.addon.hassio_api: "true"
  io.hass.addon.hassio_role: "manager"
  io.hass.addon.webui: "http://[HOST]:[PORT:7478]"