name: Alger Music Player
version: "1.0.5"
slug: alger-music-player
description: "一个第三方音乐播放器，支持网易云音乐、本地服务、桌面歌词、音乐下载、远程控制"
url: "https://github.com/algerkong/AlgerMusicPlayer"
codenotary: "notary@home-assistant.io"
arch:
  - aarch64
  - amd64
  - armv7
init: false
map:
  - config:rw
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface (HTTP)
options:
  music_api_url: "http://localhost:3001"
  log_level: "info"
schema:
  music_api_url: "str?"
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
environment:
  MUSIC_API_URL: "{music_api_url}"
image: "ghcr.io/wuwweizn/alger-music-player-{arch}"
ingress: true
ingress_port: 8080
panel_icon: "mdi:music"
panel_title: "Alger Music Player"
panel_admin: false
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"