name: OuonnkiTV
version: "1.0.0"
slug: ouonnkitv
description: 一键搭建个人影视站，基于LibreTV修改
url: https://github.com/Ouonnki/OuonnkiTV
arch:
  - amd64
  - aarch64
  - armv7
init: false
map:
  - config:rw
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Web UI
image: "ghcr.io/wuwweizn/ouonnkitv-{arch}"
options:
  initial_video_sources: ""
  tmdb_api_token: ""
  tmdb_api_base_url: "https://api.tmdb.org/3"
  tmdb_image_base_url: "https://image.tmdb.org/t/p/"
  access_password: ""
  disable_analytics: true
schema:
  initial_video_sources: str?
  tmdb_api_token: str?
  tmdb_api_base_url: str
  tmdb_image_base_url: str
  access_password: str?
  disable_analytics: bool
