build_from:
  aarch64: "alpine:3.21.3"
  amd64: "alpine:3.21.3"
  armhf: "alpine:3.21.3"
  armv7: "alpine:3.21.3"
  i386: "alpine:3.21.3"

labels:
  io.hass.name: "Alist"
  io.hass.description: "🗂️多存储文件列表/WebDAV程序 - 支持60+种存储后端的统一文件管理系统"
  io.hass.arch: "aarch64|amd64|armhf|armv7|i386"
  io.hass.type: "addon"
  io.hass.version: "3.41.0"
  maintainer: "wuwweizn"
  org.opencontainers.image.title: "Alist Home Assistant Add-on"
  org.opencontainers.image.description: "Alist文件列表程序Home Assistant加载项"
  org.opencontainers.image.source: "https://github.com/wuwweizn/wwzn-china"
  org.opencontainers.image.documentation: "https://github.com/wuwweizn/wwzn-china/tree/main/alist"
  org.opencontainers.image.author: "wuwweizn"
  org.opencontainers.image.licenses: "AGPL-3.0"

args:
  ALIST_VERSION: "3.41.0"