name: "AList"
version: "3.41.0"
slug: "alist"
description: "支持多个存储，提供Web界面并支持WebDav的文件列表程序"
url: "https://github.com/AlistGo/alist"
startup: "application"
arch:
  - "amd64"
  - "aarch64" 
  - "armv7"
image: "ghcr.io/wuwweizn/alist-{arch}"
init: false
map:
  - "share:rw"
  - "config:rw"
options:
  ssl: false
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
schema:
  ssl: "bool"
  certfile: "str"
  keyfile: "str"
ports:
  "5244/tcp": 5244
ports_description:
  "5244/tcp": "Web interface"
host_network: false
privileged:
  - "SYS_ADMIN"
  - "DAC_READ_SEARCH"
full_access: false
homeassistant_api: false
stdin: false
legacy: false
panel_icon: "mdi:folder-multiple"
panel_title: "AList"
panel_admin: true
ingress: true
ingress_port: 5244
ingress_entry: "/"
backup: "cold"
webui: "http://[HOST]:[PORT:5244]"