name: MPD
version: dev
slug: mpd
panel_icon: mdi:music-circle
description: 音乐播放器守护程序是一位免费的开源音乐播放器。它播放音频文件，组织播放列表并维护音乐数据库
url: https://github.com/Poeschl-HomeAssistant-Addons/mpd
ingress: true
ingress_port: 6680
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
image: ghcr.io/poeschl-homeassistant-addons/mpd-{arch}
init: false
audio: true
devices:
  - /dev/snd
map:
  - share:rw
  - media:rw
ports:
  6680/tcp: null
  6600/tcp: 6600
  8000/tcp: null
ports_description:
  6680/tcp: Web Frontend (Not needed with ingress feature)
  6600/tcp: MDP Connection
  8000/tcp: HTTPd Connection (if enabled)
options:
  media_folder: /media/mpd/media
  playlist_folder: /media/mpd/playlists
  volume_normalization: false
  httpd_output: false
schema:
  media_folder: match(/share/.+|/media/.+|(smb|nfs)://.+)
  playlist_folder: match(/share/.+|/media/.+|(smb|nfs)://.+)
  volume_normalization: bool
  httpd_output: bool
  verbose: bool?
  custom_config: match(/share/mpd/.+)?
