build_from:
  aarch64: ghcr.io/hassio-addons/base:14.0.3
  amd64: ghcr.io/hassio-addons/base:14.0.3
  armv7: ghcr.io/hassio-addons/base:14.0.3
args:
  REPO_URL: https://github.com/ARC-MX/sgcc_electricity_new
  REPO_REF: main