build_from:
  amd64: "ghcr.io/hassio-addons/base/amd64:15.0.7"
  aarch64: "ghcr.io/hassio-addons/base/aarch64:15.0.7"
  armv7: "ghcr.io/hassio-addons/base/armv7:15.0.7"
labels:
  org.opencontainers.image.title: "XRay for Home Assistant"
  org.opencontainers.image.description: "XRay proxy platform for bypassing network restrictions"
  org.opencontainers.image.source: "https://github.com/wuwweizn/wwzn-china"
  org.opencontainers.image.licenses: "MPL-2.0"
args:
  TEMPIO_VERSION: "2023.01.0"