# 逐步完善的config.yaml - 第二版
name: XRay Proxy
version: 1.8.24
slug: xray
description: XRay is a platform for building proxies to bypass network restrictions
url: https://github.com/XTLS/Xray-core
arch:
  - amd64
  - aarch64
  - armv7
startup: services
image: ghcr.io/wuwweizn/xray-{arch}
ports:
  "10808/tcp": 10808
  "10809/tcp": 10809
ports_description:
  "10808/tcp": SOCKS Proxy Port
  "10809/tcp": HTTP Proxy Port
options:
  log_level: warning
  config_file: /data/config/config.json
schema:
  log_level: list(debug|info|warning|error|none)
  config_file: str