name: XRay Proxy
version: 1.8.24
slug: xray
description: XRay is a platform for building proxies to bypass network restrictions
url: https://github.com/XTLS/Xray-core
webui: null
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: services
stage: stable
services:
  - xray:tcp:10808
  - xray:tcp:10809
map:
  - "10808:10808/tcp"
  - "10809:10809/tcp"
  - "config:rw"
  - "ssl:rw"
ports:
  "10808/tcp": 10808
  "10809/tcp": 10809
ports_description:
  "10808/tcp": SOCKS Proxy Port
  "10809/tcp": HTTP Proxy Port
environment:
  XRAY_CONF_PATH: /data/config/config.json
options:
  log_level: warning
  config_file: /data/config/config.json
schema:
  log_level: list(debug|info|warning|error|none)
  config_file: str
image: ghcr.io/wuwweizn/xray-{arch}
auth_api: false
ingress: false
homeassistant_api: false
host_network: false
full_access: false
apparmor: false