# 最简化的config.yaml用于调试
name: XRay Proxy
version: 1.8.24
slug: xray
description: XRay proxy platform
arch:
  - amd64
  - aarch64
  - armv7
startup: services
image: ghcr.io/wuwweizn/xray-{arch}
ports:
  "10808/tcp": 10808
  "10809/tcp": 10809
options: {}
schema: {}