name: MyIP
version: "v5.0.5"
upstream: latest
slug: myip
description: >-
  最好的IP工具箱。易于检查您的IPS，IP地理位置，检查DNS泄漏，检查WEBRTC连接，速度测试，PING测试，MTR测试，检查网站可用性，WHOIS搜索等等！
arch:
  - amd64
  - aarch64
url: "https://github.com/jdeath/homeassistant-addons"
ports:
  18966/tcp: 18966 
ports_description:
  18966/tcp: "Web Interface"
image: ghcr.io/jason5ng32/myip
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:18966]"
ingress: false
ingress_port: 18966 
