name: Alger Music Player
version: "1.0.0"
slug: alger_music
description: "Alger Music Player WebUI for HA"
arch:
  - amd64
  - arm64
startup: services
ports:
  80/tcp: 8099
webui: "http://[HOST]:[PORT:8099]"
