name: "【无为智能仓库使用说明】"
version: "8.0.0"
slug: "88wwzn88"
description: "！！请先阅读使用说明 ！！"
url: "https://github.com/wuwweizn/wwzn-china/blob/main/README.md"
startup: "services"
arch:
  - "amd64"
  - "aarch64" 
  - "armv7"
  - "i386"
  - "armhf" 
panel_icon: "mdi:folder-multiple"
panel_title: "仓库使用说明"
panel_admin: true
ingress: false
