name: Build Config Docs.md 4NENG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      # 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 安装依赖
      - name: Install dependencies
        run: pip install pyyaml tabulate

      # 生成 DOCS.md
      - name: Build Config Docs.md
        run: python 4neng/build_config_docs.py

      # 提交修改
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add 4neng/DOCS.md
          git commit -m "Update DOCS.md" || echo "No changes to commit"
          git push
