name: Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armv7]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Build for ${{ matrix.arch }}
        run: |
          mkdir -p build
          GOOS=linux GOARCH=${{ matrix.arch }} go build -o build/myapp-${{ matrix.arch }} main.go
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: build/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: builds
          path: build
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
