name: Build and Push unblock-netease-music-enhanced (Multi-Arch, Docker Hub + GHCR)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'unblock-netease-music-enhanced/**'
      - '.github/workflows/Build unblock-netease-music-enhanced.yml'
  schedule:
    # 每周日凌晨2点自动构建，确保获取最新版本
    - cron: '0 2 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            build_arch: amd64
            build_from: "ghcr.io/home-assistant/amd64-base:latest"
          - arch: arm64
            platform: linux/arm64
            build_arch: aarch64
            build_from: "ghcr.io/home-assistant/aarch64-base:latest"
          - arch: armv7
            platform: linux/arm/v7
            build_arch: armv7
            build_from: "ghcr.io/home-assistant/armv7-base:latest"
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      
      - name: Get lowercase repo owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
      
      - name: Extract VERSION from config
        id: extract_version
        run: |
          ADDON_DIR="unblock-netease-music-enhanced"
          CONFIG_PATH="${ADDON_DIR}/config.yaml"
          
          if [[ -f "$CONFIG_PATH" ]]; then
            VERSION=$(yq e ".version" "$CONFIG_PATH")
          else
            echo "❌ ERROR: $CONFIG_PATH not found!"
            exit 1
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD_ARCH=${{ matrix.build_arch }}" >> $GITHUB_ENV
          echo "💡 VERSION=$VERSION"
          echo "💡 BUILD_ARCH=${{ matrix.build_arch }}"
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push unblock-netease-music-enhanced for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: unblock-netease-music-enhanced
          file: unblock-netease-music-enhanced/Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            BUILD_FROM=${{ matrix.build_from }}
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/unblock-netease-music-enhanced-${{ env.BUILD_ARCH }}:${{ env.VERSION }}
            ghcr.io/${{ env.REPO_OWNER_LC }}/unblock-netease-music-enhanced-${{ env.BUILD_ARCH }}:latest
            ${{ secrets.DOCKER_USERNAME }}/unblock-netease-music-enhanced-${{ env.BUILD_ARCH }}:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/unblock-netease-music-enhanced-${{ env.BUILD_ARCH }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Output build info
        run: |
          echo "✅ Successfully built and pushed unblock-netease-music-enhanced"
          echo "🏷️  Version: ${{ env.VERSION }}"
          echo "🏗️  Architecture: ${{ matrix.arch }}"
          echo "📦 Docker Hub: ${{ secrets.DOCKER_USERNAME }}/unblock-netease-music-enhanced-${{ env.BUILD_ARCH }}:${{ env.VERSION }}"
          echo "📦 GHCR: ghcr.io/${{ env.REPO_OWNER_LC }}/unblock-netease-music-enhanced-${{ env.BUILD_ARCH }}:${{ env.VERSION }}"