name: Sync Lucky Docker Image from Upstream

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 同步 upstream 最新版本

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2. 登录 GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. 获取 upstream 最新 tag
      - name: Get latest upstream tag
        id: version
        run: |
          LATEST_TAG=$(git ls-remote --tags https://github.com/gdy666/lucky.git | \
            awk -F/ '{print $3}' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
          echo "Latest upstream tag: $LATEST_TAG"
          VERSION=${LATEST_TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 4. 检查镜像是否已存在
      - name: Check if image exists
        id: check_image
        run: |
          set +e
          docker manifest inspect ghcr.io/wuwweizn/lucky:${{ steps.version.outputs.version }} > /dev/null
          if [ $? -eq 0 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # 5. 停止如果镜像已存在
      - name: Stop if image exists
        if: steps.check_image.outputs.exists == 'true'
        run: |
          echo "Image ghcr.io/wuwweizn/lucky:${{ steps.version.outputs.version }} already exists. Exiting."
          exit 0

      # 6. 拉取并推送 upstream 镜像
      - name: Pull and Push Image
        run: |
          echo "Pulling upstream image..."
          docker pull ghcr.io/gdy666/lucky:${{ steps.version.outputs.version }}

          echo "Tagging image..."
          docker tag ghcr.io/gdy666/lucky:${{ steps.version.outputs.version }} ghcr.io/wuwweizn/lucky:${{ steps.version.outputs.version }}
          docker tag ghcr.io/gdy666/lucky:${{ steps.version.outputs.version }} ghcr.io/wuwweizn/lucky:latest

          echo "Pushing images..."
          docker push ghcr.io/wuwweizn/lucky:${{ steps.version.outputs.version }}
          docker push ghcr.io/wuwweizn/lucky:latest
