name: Build and Push ddnsto add-on

on:
  push:
    branches:
      - main
    paths:
      - 'ddnsto/**'
      - '.github/workflows/build-ddnsto.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, aarch64, armv7]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: ./ddnsto
          file: ./ddnsto/Dockerfile
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ddnsto-${{ matrix.arch }}:latest
            ghcr.io/${{ github.repository_owner }}/ddnsto-${{ matrix.arch }}:1.0.0
