name: Build Lucky Multi-Arch Docker Image from Upstream

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 检查 upstream 最新 tag

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2. 登录 GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. 设置 QEMU 支持多架构
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 4. 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 5. 获取 upstream 最新 tag
      - name: Get latest upstream tag
        id: version
        run: |
          LATEST_TAG=$(git ls-remote --tags https://github.com/gdy666/lucky.git | \
            awk -F/ '{print $3}' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
          echo "Latest upstream tag: $LATEST_TAG"
          VERSION=${LATEST_TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 6. 检查镜像是否已存在
      - name: Check if image exists
        id: check_image
        run: |
          set +e
          docker manifest inspect ghcr.io/wuwweizn/lucky:${{ steps.version.outputs.version }} > /dev/null
          if [ $? -eq 0 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # 7. 停止如果镜像已存在
      - name: Stop if image exists
        if: steps.check_image.outputs.exists == 'true'
        run: |
          echo "Image ghcr.io/wuwweizn/lucky:${{ steps.version.outputs.version }} already exists. Exiting."
          exit 0

      # 8. 构建并推送 multi-arch 镜像
      - name: Build and Push Multi-Arch Images
        run: |
          ARCHS=("amd64" "arm64" "armv7")
          for arch in "${ARCHS[@]}"; do
            echo "Pulling upstream image for $arch"
            docker pull --platform=linux/$arch ghcr.io/gdy666/lucky:${{ steps.version.outputs.version }}
            
            echo "Tagging image for $arch"
            docker tag ghcr.io/gdy666/lucky:${{ steps.version.outputs.version }} ghcr.io/wuwweizn/lucky:${{ steps.version.outputs.version }}-$arch
            
            echo "Pushing image for $arch"
            docker push ghcr.io/wuwweizn/lucky:${{ steps.version.outputs.version }}-$arch
          done

          # 创建 latest 标签（指向最新 upstream）
          docker pull ghcr.io/gdy666/lucky:${{ steps.version.outputs.version }}
          docker tag ghcr.io/gdy666/lucky:${{ steps.version.outputs.version }} ghcr.io/wuwweizn/lucky:latest
          docker push ghcr.io/wuwweizn/lucky:latest
