name: Build Lucky Add-on

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # 每天早上8点自动检查更新

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest Lucky version
        id: lucky
        run: |
          LATEST=$(curl -s https://api.github.com/repos/gdy666/lucky/releases/latest | grep '"tag_name"' | cut -d '"' -f4)
          echo "version=${LATEST}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Update config.json version
        run: |
          sed -i 's/"version": ".*"/"version": "${{ steps.lucky.outputs.version }}"/' lucky/config.json

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ./lucky
          file: ./lucky/Dockerfile
          push: true
          tags: |
            wuwweizn/lucky:${{ steps.lucky.outputs.version }}
            wuwweizn/lucky:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
