name: Build and Push to GHCR (Multi-Arch, Multi-Addon)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'wwzn-china/**'
      - '.github/workflows/builder.yml'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.set-addons.outputs.addons }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List addon directories
        id: set-addons
        run: |
          ADDONS=$(ls -d wwzn-china/*/ | xargs -n1 basename | tr '\n' ',' | sed 's/,$//')
          echo "addons=$ADDONS" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        addon: [${{ fromJson('["' + needs.prepare.outputs.addons.replace(',', '","') + '"]') }}]
    permissions:
      contents: read
      packages: write
    env:
      DEFAULT_BUILD_FROM_amd64: alpine:3.21.3
      DEFAULT_BUILD_FROM_aarch64: alpine:3.21.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq yq

      - name: Get lowercase repo owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Extract BUILD_FROM, BUILD_ARCH and VERSION
        id: extract_meta
        run: |
          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            BUILD_ARCH="aarch64"
          else
            BUILD_ARCH="${{ matrix.arch }}"
          fi

          ADDON_DIR="wwzn-china/${{ matrix.addon }}"
          YAML_PATH="${ADDON_DIR}/build.yaml"
          CONFIG_PATH="${ADDON_DIR}/config.json"

          if [[ -f "$YAML_PATH" ]]; then
            BUILD_FROM=$(yq e ".build_from.${BUILD_ARCH}" "$YAML_PATH")
          else
            DEFAULT_VAR_NAME="DEFAULT_BUILD_FROM_${BUILD_ARCH}"
            BUILD_FROM="${!DEFAULT_VAR_NAME}"
          fi

          if [[ -f "$CONFIG_PATH" ]]; then
            VERSION=$(jq -r .version "$CONFIG_PATH")
          else
            echo "❌ ERROR: $CONFIG_PATH not found!"
            exit 1
          fi

          echo "BUILD_ARCH=$BUILD_ARCH" >> $GITHUB_ENV
          echo "BUILD_FROM=$BUILD_FROM" >> $GITHUB_ENV
          echo "ADDON_NAME=${{ matrix.addon }}" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          echo "💡 BUILD_FROM=$BUILD_FROM"
          echo "💡 BUILD_ARCH=$BUILD_ARCH"
          echo "💡 VERSION=$VERSION"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.addon }} for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ 'wwzn-china/' + matrix.addon }}
          file: ${{ 'wwzn-china/' + matrix.addon + '/Dockerfile' }}
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.ADDON_NAME }}-${{ env.BUILD_ARCH }}:${{ env.VERSION }}
          build-args: |
            BUILD_FROM=${{ env.BUILD_FROM }}
            BUILD_ARCH=${{ env.BUILD_ARCH }}
